name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build_windows:
    name: Build Windows Desktop
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build HackerNews.Desktop
      run: dotnet build HackerNews.Desktop/HackerNews.Desktop.csproj --configuration Release
  build_windows_browser:
    name: Build Windows Browser
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build HackerNews.Browser
      run: dotnet build HackerNews.Browser/HackerNews.Browser.csproj --configuration Release
  build_windows_android:
    name: Build Windows Android
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '21'
    - name: Install workloads
      run: dotnet workload install android
    - name: Build HackerNews.Android
      run: dotnet build HackerNews.Android/HackerNews.Android.csproj --configuration Release
  build_windows_ios:
    name: Build Windows iOS
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install ios
    - name: Build HackerNews.iOS
      run: dotnet build HackerNews.iOS/HackerNews.iOS.csproj --configuration Release
  build_linux_desktop:
    name: Build Ubuntu Desktop
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build HackerNews.Desktop
      run: dotnet build HackerNews.Desktop/HackerNews.Desktop.csproj --configuration Release
  build_linux_android:
    name: Build Ubuntu Android
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install android
    - name: Build HackerNews.Android
      run: dotnet build HackerNews.Android/HackerNews.Android.csproj --configuration Release
  build_linux_browser:
    name: Build Ubuntu Browser
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build HackerNews.Browser
      run: dotnet build HackerNews.Browser/HackerNews.Browser.csproj --configuration Release
  build_macos_desktop:
    name: Build macOS Desktop
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build HackerNews.Desktop
      run: dotnet build HackerNews.Desktop/HackerNews.Desktop.csproj --configuration Release
  build_macos_ios:
    name: Build macOS iOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_15.1.app
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install ios
    - name: Build HackerNews.iOS
      run: dotnet build HackerNews.iOS/HackerNews.iOS.csproj --configuration Release
  build_macos_browser:
    name: Build macOS Browser
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build HackerNews.Browser
      run: dotnet build HackerNews.Browser/HackerNews.Browser.csproj --configuration Release
